# Generated by Django 6.0.3 on 2026-04-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_pet", models.CharField(max_length=100)),
                ("raca_pet", models.CharField(max_length=100)),
                (
                    "porte_pet",
                    models.CharField(
                        choices=[
                            ("pequeno", "Pequeno"),
                            ("medio", "Médio"),
                            ("grande", "Grande"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
