# Generated by Django 6.0.3 on 2026-05-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agendamento_realizacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_realizacao',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='hora_realizacao',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='recorrente',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='criado_em',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pet'),
        ),
    ]
