# Generated by Django 6.0.3 on 2026-04-11 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora', models.DateTimeField()),
                ('possui_logistica', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Espécie',
                'verbose_name_plural': 'Espécies',
            },
        ),
        migrations.CreateModel(
            name='Porte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20, unique=True)),
                ('peso_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='StatusAgendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status de agendamento',
                'verbose_name_plural': 'Status de agendamentos',
            },
        ),
        migrations.CreateModel(
            name='StatusLogistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Status de logística',
                'verbose_name_plural': 'Status de logística',
            },
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de atendimento',
                'verbose_name_plural': 'Tipos de atendimento',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_envio', models.DateTimeField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('falhou', 'Falhou')], default='pendente', max_length=20)),
                ('mensagem', models.TextField()),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.agendamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, help_text='Usado para calcular a idade atual do pet.', null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('observacoes_gerais', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.cliente')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.especie')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAtendimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.agendamento')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.pet')),
            ],
            options={
                'verbose_name': 'Histórico de atendimento',
                'verbose_name_plural': 'Histórico de atendimentos',
                'ordering': ['-data'],
            },
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.pet'),
        ),
        migrations.CreateModel(
            name='PetSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.pet')),
            ],
            options={
                'verbose_name': 'Saúde do pet',
                'verbose_name_plural': 'Saúde dos pets',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.especie')),
                ('porte_referencia', models.ForeignKey(blank=True, help_text='Porte típico desta raça. O porte efetivo do pet é calculado pelo peso.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.porte')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='raca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.raca'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.statusagendamento'),
        ),
        migrations.CreateModel(
            name='LogisticaAgendamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('horario_busca', models.DateTimeField(blank=True, null=True)),
                ('horario_entrega', models.DateTimeField(blank=True, null=True)),
                ('custo_transporte', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servicos.agendamento')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicos.endereco')),
                ('status_logistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.statuslogistica')),
                ('tipo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.tipoatendimento')),
            ],
            options={
                'verbose_name': 'Logística de agendamento',
                'verbose_name_plural': 'Logísticas de agendamentos',
            },
        ),
        migrations.CreateModel(
            name='AgendamentoServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.agendamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Serviço do agendamento',
                'verbose_name_plural': 'Serviços do agendamento',
                'unique_together': {('agendamento', 'servico')},
            },
        ),
        migrations.CreateModel(
            name='ServicoPorte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao_estimada', models.IntegerField(help_text='Duração em minutos')),
                ('porte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.porte')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servico')),
            ],
            options={
                'verbose_name': 'Preço por porte',
                'verbose_name_plural': 'Preços por porte',
                'unique_together': {('servico', 'porte')},
            },
        ),
    ]
